### ISSUE TITLE
Autoencoder: Sparse AEに対応

### ISSUE THREAD

**Issue by uchikun2493** [aist9/autoencoder#2]

**Comment by uchikun2493** [comment]
誤差の計算と引数の設定で対応する

**Comment by aist9** [comment]
trainerで実装するとラッパーを挟むので、ラッパーに対する引数とかで対応させると良さそう？
スパース対応だと隠れ層の出力を貰わないと行けないけど

**Comment by uchikun2493** [comment]
feature/trainerで対応後、masterに反映する

**Comment by uchikun2493** [comment]
trainer対応のときに組み込んだ
